### ISSUE TITLE
update build configuration with latest vsce

### ISSUE THREAD

**Issue by malud** [avenga/couper-vscode#122]
`npm WARN deprecated vsce@2.15.0: vsce has been renamed to @vscode/vsce. Install using @vscode/vsce instead.`

**Comment by malud** [comment]
## Migration plan

The workflow currently uses two separate actions/steps for publishing:

1. `lannonbr/vsce-action@4.0.0` — for VS Code Marketplace (uses deprecated `vsce`)
2. `HaaLeo/publish-vscode-extension@v1` — for Open VSX Registry

`HaaLeo/publish-vscode-extension@v2` supports publishing to **both** registries and already uses `@vscode/vsce` (not the deprecated `vsce`). So we can consolidate both steps into one action.

### Proposed `release.yaml` change

Replace the two publish steps:

```yaml
    - name: 'Publish to Microsoft Marketplace'
      uses: lannonbr/vsce-action@4.0.0
      with:
        args: "publish -p $VSCE_TOKEN"
      env:
        VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
    - name: 'Publish to Open VSX Registry'
      uses: HaaLeo/publish-vscode-extension@v1
      with:
        pat: ${{ secrets.OPEN_VSX_TOKEN }}
```

with a single step:

```yaml
    - name: 'Publish to VS Code Marketplace and Open VSX Registry'
      uses: HaaLeo/publish-vscode-extension@v2
      with:
        pat: ${{ secrets.OPEN_VSX_TOKEN }}
        registryUrl: https://open-vsx.org
        vsceToken: ${{ secrets.VSCE_TOKEN }}
```

This drops the `lannonbr/vsce-action` dependency entirely and removes the deprecated `vsce` usage.
